Fix documentation #21
btsdigital/bot-api-contract pull request #23
Opened 2019-12-06 06:51 UTC by alehodro

## PR title

* added new audio, video, image, avatar, contact, document, media, user description pages;
* deleted unnecessary botcommand.png image;
* updated retrieveUpdates.png image;
* updated contribution, ChangeGroupTitle, ChangeGroupAvatar, ChangeGroupDescription, channeladminadded, channeladmindeleted, channelpermissiongranted, commandrequest, DeleteMessage, EditContainerMessage, EditMessage, endpoints, foreclosed, formmessagesent, form submitted, ForwardMessage, getting update, getWebhookInfo, inlinecommandselected, input contact, InputMedia, KickFromGroup, make requests, message, message edited, messageforwardmetadata,messageidassigned, newchannelsubscriber, quickbuttoncommand, quickbuttonselected, replycommand, retrieveUpdate, SendContactMessage, SendContainerMessage, SendMessage, SendUiState, SetWebhook, uistate, update response ( fixed grammar, enhanced content, added web-links).

Reviewers:
* @navi89mai
* @mustafin
* @vseko

2019-12-06 11:41 UTC, yerassyl94 requested changes
please resolve comments

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/SendUiState.md
> + 	 		"id": "ga018bae-e3e7-11e8-a458-7a609eaf8200"
please remove personal token

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/SendUiState.md
> + 	 		"id": "ga018bae-e3e7-11e8-a458-7a609eaf8200"
please remove personal token
```suggestion
 	 		"id": "dialog_id"
```

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/audio.md
> +      "fileId":"361a63f1-abbd-4026-b4fb-96e1d70c5bd1",
please remove token
```suggestion
      "fileId": <your_file_id>,
```

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/avatar.md
> +      "fileId":"361a63f1-abbd-4026-b4fb-96e1d70c5bd1",
please remove id

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/avatar.md
> +      "fileId":"382f03e6-12cd-4ef4-a88e-95a4ad05d350",
please remove id

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/contact.md
> +                        "id" : "f1a6b389-40e2-4318-adbc-3b38c57bf1f4",
please remove id

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/contact.md
> +                        "phoneNumber" : "+77077661234",
please remove personal info

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/contact.md
> +                            "fileId" : "361a63f1-abbd-4026-b4fb-96e1d70c5bd1",
please remove id

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/contact.md
> +                            "fileId" : "382f03e6-12cd-4ef4-a88e-95a4ad05d350",
please remove id

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/contact.md
> +      "phoneNumber":"+77018981221"
please remove personal info

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/document.md
> +      "fileId":"361a63f1-abbd-4026-b4fb-96e1d70c5bd1",
please remove id

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/formmessagesent.md
> +                               "id": "3a17518d-63d4-4d63-9c46-9c312588779a",
please remove id

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/formmessagesent.md
> +                           "additionalMetadata": "{\"data_template_result\":\"77057252478\",\"private_data\":{\"value\":{\"phone_number\":\"+77077221478\",\"metadata\":\"XXX\"}},\"hidden_metadata\":\
please remove personal info

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/image.md
> +      "fileId":"361a63f1-abbd-4026-b4fb-96e1d70c5bd1",
please remove id

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/inputmedia.md
>   		"fileId":"08d5251b-0b86-11ea-9162-ee73f85aba69",
please remove id

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/quickbuttoncommand.md
> + 		 			"metadata":"{\r\n   \"action\" : \"redirect_call\",\r\n   \"data_template\" : \"+77072771478\"\r\n}"
please remove personal info

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/user.md
> +          "phoneNumber" : "+77077661234",
please remove personal info

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/user.md
> +              "fileId" : "361a63f1-abbd-4026-b4fb-96e1d70c5bd1",
please remove id

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/user.md
> +              "fileId" : "382f03e6-12cd-4ef4-a88e-95a4ad05d350",
please remove id

2019-12-06 11:41 UTC, yerassyl94 commented on docs/pages/model/video.md
> +      "fileId":"361a63f1-abbd-4026-b4fb-96e1d70c5bd1",
please remove id

2019-12-06 11:45 UTC, alehodro commented on docs/pages/model/avatar.md
> +      "fileId":"361a63f1-abbd-4026-b4fb-96e1d70c5bd1",
This is randomly generated uuid

2019-12-06 11:48 UTC, alehodro commented on docs/pages/model/avatar.md
> +      "fileId":"382f03e6-12cd-4ef4-a88e-95a4ad05d350",
This is randomly generated uuid

2019-12-06 11:57 UTC, yerassyl94 commented on docs/pages/model/contact.md
> +                        "id" : "f1a6b389-40e2-4318-adbc-3b38c57bf1f4",
it is a randomly generated uuid

2019-12-09 08:03 UTC, alehodro commented on docs/pages/model/contact.md
> +                        "phoneNumber" : "+77077661234",
Fixed

2019-12-09 08:03 UTC, alehodro commented on docs/pages/model/contact.md
> +      "phoneNumber":"+77018981221"
Fixed

2019-12-09 08:03 UTC, alehodro commented on docs/pages/model/formmessagesent.md
> +                           "additionalMetadata": "{\"data_template_result\":\"77057252478\",\"private_data\":{\"value\":{\"phone_number\":\"+77077221478\",\"metadata\":\"XXX\"}},\"hidden_metadata\":\
Fixed

2019-12-09 08:03 UTC, alehodro commented on docs/pages/model/quickbuttoncommand.md
> + 		 			"metadata":"{\r\n   \"action\" : \"redirect_call\",\r\n   \"data_template\" : \"+77072771478\"\r\n}"
Fixed

2019-12-09 08:04 UTC, alehodro commented on docs/pages/model/user.md
> +          "phoneNumber" : "+77077661234",
Fixed

2019-12-10 08:50 UTC, yerassyl94 requested changes

2019-12-10 08:50 UTC, yerassyl94 commented on docs/pages/model/formmessagesent.md
> +                           "additionalMetadata": "{\"data_template_result\":\"7**********\",\"private_data\":{\"value\":{\"phone_number\":\"+77077221478\",\"metadata\":\"XXX\"}},\"hidden_metadata\":\
phone number)

2019-12-10 09:01 UTC, alehodro commented on docs/pages/model/formmessagesent.md
> +                           "additionalMetadata": "{\"data_template_result\":\"7**********\",\"private_data\":{\"value\":{\"phone_number\":\"+77077221478\",\"metadata\":\"XXX\"}},\"hidden_metadata\":\
fixed

2019-12-10 09:08 UTC, yerassyl94 approved these changes

2019-12-10 09:08 UTC, merged